// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"canarails.dev/database/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAppDeploy(db *gorm.DB, opts ...gen.DOOption) appDeploy {
	_appDeploy := appDeploy{}

	_appDeploy.appDeployDo.UseDB(db, opts...)
	_appDeploy.appDeployDo.UseModel(&models.AppDeploy{})

	tableName := _appDeploy.appDeployDo.TableName()
	_appDeploy.ALL = field.NewAsterisk(tableName)
	_appDeploy.ID = field.NewUint(tableName, "id")
	_appDeploy.CreatedAt = field.NewTime(tableName, "created_at")
	_appDeploy.UpdatedAt = field.NewTime(tableName, "updated_at")
	_appDeploy.DeletedAt = field.NewField(tableName, "deleted_at")
	_appDeploy.Replicas = field.NewInt(tableName, "replicas")
	_appDeploy.ImageName = field.NewString(tableName, "image_name")
	_appDeploy.AppVariantID = field.NewUint(tableName, "app_variant_id")
	_appDeploy.AppVariant = appDeployBelongsToAppVariant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AppVariant", "models.AppVariant"),
		App: struct {
			field.RelationField
			AppVariants struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("AppVariant.App", "models.App"),
			AppVariants: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AppVariant.App.AppVariants", "models.AppVariant"),
			},
		},
	}

	_appDeploy.fillFieldMap()

	return _appDeploy
}

type appDeploy struct {
	appDeployDo appDeployDo

	ALL          field.Asterisk
	ID           field.Uint
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field
	Replicas     field.Int
	ImageName    field.String
	AppVariantID field.Uint
	AppVariant   appDeployBelongsToAppVariant

	fieldMap map[string]field.Expr
}

func (a appDeploy) Table(newTableName string) *appDeploy {
	a.appDeployDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appDeploy) As(alias string) *appDeploy {
	a.appDeployDo.DO = *(a.appDeployDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appDeploy) updateTableName(table string) *appDeploy {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.Replicas = field.NewInt(table, "replicas")
	a.ImageName = field.NewString(table, "image_name")
	a.AppVariantID = field.NewUint(table, "app_variant_id")

	a.fillFieldMap()

	return a
}

func (a *appDeploy) WithContext(ctx context.Context) IAppDeployDo {
	return a.appDeployDo.WithContext(ctx)
}

func (a appDeploy) TableName() string { return a.appDeployDo.TableName() }

func (a appDeploy) Alias() string { return a.appDeployDo.Alias() }

func (a appDeploy) Columns(cols ...field.Expr) gen.Columns { return a.appDeployDo.Columns(cols...) }

func (a *appDeploy) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appDeploy) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["replicas"] = a.Replicas
	a.fieldMap["image_name"] = a.ImageName
	a.fieldMap["app_variant_id"] = a.AppVariantID

}

func (a appDeploy) clone(db *gorm.DB) appDeploy {
	a.appDeployDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appDeploy) replaceDB(db *gorm.DB) appDeploy {
	a.appDeployDo.ReplaceDB(db)
	return a
}

type appDeployBelongsToAppVariant struct {
	db *gorm.DB

	field.RelationField

	App struct {
		field.RelationField
		AppVariants struct {
			field.RelationField
		}
	}
}

func (a appDeployBelongsToAppVariant) Where(conds ...field.Expr) *appDeployBelongsToAppVariant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a appDeployBelongsToAppVariant) WithContext(ctx context.Context) *appDeployBelongsToAppVariant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a appDeployBelongsToAppVariant) Session(session *gorm.Session) *appDeployBelongsToAppVariant {
	a.db = a.db.Session(session)
	return &a
}

func (a appDeployBelongsToAppVariant) Model(m *models.AppDeploy) *appDeployBelongsToAppVariantTx {
	return &appDeployBelongsToAppVariantTx{a.db.Model(m).Association(a.Name())}
}

type appDeployBelongsToAppVariantTx struct{ tx *gorm.Association }

func (a appDeployBelongsToAppVariantTx) Find() (result *models.AppVariant, err error) {
	return result, a.tx.Find(&result)
}

func (a appDeployBelongsToAppVariantTx) Append(values ...*models.AppVariant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a appDeployBelongsToAppVariantTx) Replace(values ...*models.AppVariant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a appDeployBelongsToAppVariantTx) Delete(values ...*models.AppVariant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a appDeployBelongsToAppVariantTx) Clear() error {
	return a.tx.Clear()
}

func (a appDeployBelongsToAppVariantTx) Count() int64 {
	return a.tx.Count()
}

type appDeployDo struct{ gen.DO }

type IAppDeployDo interface {
	gen.SubQuery
	Debug() IAppDeployDo
	WithContext(ctx context.Context) IAppDeployDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppDeployDo
	WriteDB() IAppDeployDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppDeployDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppDeployDo
	Not(conds ...gen.Condition) IAppDeployDo
	Or(conds ...gen.Condition) IAppDeployDo
	Select(conds ...field.Expr) IAppDeployDo
	Where(conds ...gen.Condition) IAppDeployDo
	Order(conds ...field.Expr) IAppDeployDo
	Distinct(cols ...field.Expr) IAppDeployDo
	Omit(cols ...field.Expr) IAppDeployDo
	Join(table schema.Tabler, on ...field.Expr) IAppDeployDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppDeployDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppDeployDo
	Group(cols ...field.Expr) IAppDeployDo
	Having(conds ...gen.Condition) IAppDeployDo
	Limit(limit int) IAppDeployDo
	Offset(offset int) IAppDeployDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppDeployDo
	Unscoped() IAppDeployDo
	Create(values ...*models.AppDeploy) error
	CreateInBatches(values []*models.AppDeploy, batchSize int) error
	Save(values ...*models.AppDeploy) error
	First() (*models.AppDeploy, error)
	Take() (*models.AppDeploy, error)
	Last() (*models.AppDeploy, error)
	Find() ([]*models.AppDeploy, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AppDeploy, err error)
	FindInBatches(result *[]*models.AppDeploy, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AppDeploy) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppDeployDo
	Assign(attrs ...field.AssignExpr) IAppDeployDo
	Joins(fields ...field.RelationField) IAppDeployDo
	Preload(fields ...field.RelationField) IAppDeployDo
	FirstOrInit() (*models.AppDeploy, error)
	FirstOrCreate() (*models.AppDeploy, error)
	FindByPage(offset int, limit int) (result []*models.AppDeploy, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppDeployDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appDeployDo) Debug() IAppDeployDo {
	return a.withDO(a.DO.Debug())
}

func (a appDeployDo) WithContext(ctx context.Context) IAppDeployDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appDeployDo) ReadDB() IAppDeployDo {
	return a.Clauses(dbresolver.Read)
}

func (a appDeployDo) WriteDB() IAppDeployDo {
	return a.Clauses(dbresolver.Write)
}

func (a appDeployDo) Session(config *gorm.Session) IAppDeployDo {
	return a.withDO(a.DO.Session(config))
}

func (a appDeployDo) Clauses(conds ...clause.Expression) IAppDeployDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appDeployDo) Returning(value interface{}, columns ...string) IAppDeployDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appDeployDo) Not(conds ...gen.Condition) IAppDeployDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appDeployDo) Or(conds ...gen.Condition) IAppDeployDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appDeployDo) Select(conds ...field.Expr) IAppDeployDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appDeployDo) Where(conds ...gen.Condition) IAppDeployDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appDeployDo) Order(conds ...field.Expr) IAppDeployDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appDeployDo) Distinct(cols ...field.Expr) IAppDeployDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appDeployDo) Omit(cols ...field.Expr) IAppDeployDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appDeployDo) Join(table schema.Tabler, on ...field.Expr) IAppDeployDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appDeployDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppDeployDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appDeployDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppDeployDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appDeployDo) Group(cols ...field.Expr) IAppDeployDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appDeployDo) Having(conds ...gen.Condition) IAppDeployDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appDeployDo) Limit(limit int) IAppDeployDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appDeployDo) Offset(offset int) IAppDeployDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appDeployDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppDeployDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appDeployDo) Unscoped() IAppDeployDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appDeployDo) Create(values ...*models.AppDeploy) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appDeployDo) CreateInBatches(values []*models.AppDeploy, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appDeployDo) Save(values ...*models.AppDeploy) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appDeployDo) First() (*models.AppDeploy, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AppDeploy), nil
	}
}

func (a appDeployDo) Take() (*models.AppDeploy, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AppDeploy), nil
	}
}

func (a appDeployDo) Last() (*models.AppDeploy, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AppDeploy), nil
	}
}

func (a appDeployDo) Find() ([]*models.AppDeploy, error) {
	result, err := a.DO.Find()
	return result.([]*models.AppDeploy), err
}

func (a appDeployDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AppDeploy, err error) {
	buf := make([]*models.AppDeploy, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appDeployDo) FindInBatches(result *[]*models.AppDeploy, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appDeployDo) Attrs(attrs ...field.AssignExpr) IAppDeployDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appDeployDo) Assign(attrs ...field.AssignExpr) IAppDeployDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appDeployDo) Joins(fields ...field.RelationField) IAppDeployDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appDeployDo) Preload(fields ...field.RelationField) IAppDeployDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appDeployDo) FirstOrInit() (*models.AppDeploy, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AppDeploy), nil
	}
}

func (a appDeployDo) FirstOrCreate() (*models.AppDeploy, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AppDeploy), nil
	}
}

func (a appDeployDo) FindByPage(offset int, limit int) (result []*models.AppDeploy, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appDeployDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appDeployDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appDeployDo) Delete(models ...*models.AppDeploy) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appDeployDo) withDO(do gen.Dao) *appDeployDo {
	a.DO = *do.(*gen.DO)
	return a
}
